[build]
publish = "."

[functions]
directory = "server/netlify/functions"
included_files = ["knowledge/hotel-info.txt"]

[[redirects]]
from = "/"
to = "/client/index.html"
status = 200

[[redirects]]
from = "/images/*"
to = "/public/images/:splat"
status = 200

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/chat"
status = 200